#!/bin/bash

PERCENT=`iwconfig wlp3s0 | grep "Link Quality" | grep -o -E "[0-9]{1,2}\/[0-9]{1,3}"`

PERCENT=`echo "scale=2;$PERCENT" | bc`

unset scale

PERCENT=`echo $PERCENT*100 | bc | cut -d"." -f1`

NETWORK=`nmcli -t -f active,ssid dev wifi | grep yes | cut -d: -f2`

echo "$NETWORK ($PERCENT%)"
